### ISSUE TITLE
Initial Feedback from Colleagues

### ISSUE THREAD

**Issue by kemitchell** [commonform/commonform-license#1]
@anseljh, @brianwc, @harrykzhou, @jboehmig, @morninj, @timhwang, and @twneale,

I'd appreciate your feedback on this project, which I suspect is of mutual interest. The goal is to craft an MIT-style public license—“permissive” or “academic” as opposed to “reciprocal” or “share-alike”—for those cases where the law might otherwise imply unfortunate professional responsibility defaults in addition to copyright exclusivity and warranties. One hard problem is doing and saying enough to make lawyers happy without spilling so much ink that lay users couldn't trust it. The other, I think, is doing enough by disclaimer to assuage fears of malpractice, uncertified specialization claims, and attorney advertising problems. So, in a nutshell: all the drafting problems we know and love from engagement letters, but absolutely not engaging anyone to do anything ever at all.

I'd be particularly interested in your feedback on the general idea of incorporating a "no legal advice" disclaimer (and an obligation to reproduce that disclaimer in copies) into the license itself. This is in the nature of the advertising prohibition of the [3-clause BSD license](http://opensource.org/licenses/BSD-3-Clause) or an [Apache-2.0](http://opensource.      org/licenses/Apache-2.0)-style NOTICES file devoted to disclaimer, rather than attribution. It is different from, say, what Jason did with [Series Seed](https://github.com/seriesseed/equity), with a content-neutral ([CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode)) license side-by-side with a separate disclaimer.

Other "document dumps", usually in Microsoft Word format, prepend a notice or license to the document itself. Stephen Guth's SaaS MSA template is one example, and I've included the license he used in this repository as "prior art", along with other examples. That approach won't work to the extent we start sharing forms as data, which you may know as [a fairly substantial a side project of mine](https://commonform.github.io).

The closest to a purpose-built, semi-permissive license for a legal document that I've seen is section 16 to Larry Rosen's Open Software License and Academic Free License, also in the prior art folder. I've sent Larry a cold e-mail asking whether any legal document-specific concerns informed his choice of terms for that section. If Nimmer and American Family Life Insurance Company of Columbus (AFLAC) v. Assurant, Inc., No. 1:05-cv-01462-BBM (N.D. Ga. Jan. 11, 2006) are any indication, the answer may be "no, because there aren't any". Ken Adams has a [nice article on the subject](http://www.adamsdrafting.com/wp/wp-content/uploads/2013/03/Copyright-NYLJ-8.23.06.pdf).

In any event, I welcome your comments, questions, or proposals you may have. If GitHub is unfamiliar of your input is more in the nature of discussion or criticism than a redline, you should feel free to [open a new issue](https://github.com/commonform/license/issues/new) (which works a bit like a message board post), or to contact me by e-mail if you'd prefer to keep your comments private. I will be more than happy to credit everyone involved, provided of course that contributors of language are alright licensing the license under its own terms when the time comes. A fun bit of recursion that'll be.

Best to all,
K

**Comment by kemitchell** [comment]
@morninj: Forgive me for omitting you from the @-mention list above. I'd greatly appreciate any feedback you may have as well.

**Comment by morninj** [comment]
Happy to help, but it will have to wait until the end of the semester (~three weeks).

**Comment by kemitchell** [comment]
I am seriously considering an avowedly "plain English" approach. Work in that direction is available at #2.

**Comment by kemitchell** [comment]
@HazardJ, you may also be interested in this project. I'd welcome your input.
